src/Entity/Picture.php
<?php

namespace App\Entity;

use App\Repository\PictureRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PictureRepository::class)
 * @Vich\Uploadable
 */
class Picture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="featured_images", fileNameProperty="image")
     * @var File
     */

    private $imageFile;
    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="pictures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image):self
    {
        $this->image = $image;

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile = null): self
    {
        $this->imageFile = $imageFile;

        if(null !== $imageFile){
            $this->updated_at = new \DateTimeImmutable();
        }
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Categorie
    {
        return $this->category;
    }

    public function setCategory(?Categorie $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsValidated(): ?bool
    {
        return $this->is_validated;
    }

    public function setIsValidated(bool $is_validated): self
    {
        $this->is_validated = $is_validated;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Picture;
use App\Entity\Categorie;
use Symfony\Component\HttpFoundation\Request; // Nous avons besoin d'accéder à la requête pour obtenir le numéro de page
use Knp\Component\Pager\PaginatorInterface; // Nous appelons le bundle KNP Paginator


class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
        // équivalent : SELECT * FROM picture
        // findAll() retourne tous les résultats trouvés dans la table 'pictures'
        // $pictures = $this->getDoctrine()->getRepository(Picture::class)->findAll();
        $resultsPictures = $this->getDoctrine()->getRepository(Picture::class)->findBy(['is_validated' => true],['created_at' => 'desc']);
        $page =  $request->query->getInt('page', 1); // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
        $pictures = $paginator->paginate( 
        //paginate attend 3 résultats:
            $resultsPictures, // Requête contenant les données à paginer (ici nos images)
            $page === 0 ? 1 : $page, // verification de la valeur dans l'url
            10 // Nombre de résultats par page
        );

        $categories = $this->getDoctrine()->getRepository(Categorie::class)->findAll();

        return $this->render('home/index.html.twig', [
            'pictures' => $pictures,
            'categories' => $categories,
          
            ]);
    }

    /** 
     * On donne un nom à la page, le name doit etre unique pour pouvoir l'utiliser dans les liens
     * @Route("/category/{id}", name="categorie")
     */
    public function categoriePage($id,Request $request, PaginatorInterface $paginator){

        $categoriePage = $this->getDoctrine()->getRepository(Categorie::class)->findOneBy(['id' => $id]);
        $query=$this->getDoctrine()->getRepository(Picture::class)->findBy([
            
            'category' => $categoriePage,
            'is_validated' => true
            
            ]);

        if(!$categoriePage){
            throw $this-> createNotFoundException('La catégorie n\'existe pas');
        }
        
        $page =  $request->query->getInt('page', 1);
        $pictures = $paginator->paginate( 
           $query,
            $page === 0 ? 1 : $page,
            10
        );

        $categories = $this->getDoctrine()->getRepository(Categorie::class)->findAll();

        // retourne la vue associée à cette route (méthode)
        return $this->render('home/category.html.twig', [
                'categoriePage' => $categoriePage,
                'pictures' => $pictures,
                'categories' => $categories
       
        ]);
    }
    /** 
     * On donne un nom à la page, le name doit etre unique pour pouvoir l'utiliser dans les liens
     * le requirements sert à valider le type de la donnée que l'on va recevoir. ici id(int)
     * @Route("/categoryimg/{id}", name="showImage", requirements={"id"="\d+"})
     */
    public function showImage($id,Request $request, PaginatorInterface $paginator){

        $showImage = $this->getDoctrine()->getRepository(Picture::class)->findOneBy(['id' => $id]);
        $query = $this->getDoctrine()->getRepository(Picture::class)->findBy([
            'category' =>$showImage -> getCategory(),
            'is_validated' => true

        ]);


        if(!$showImage){
            throw $this-> createNotFoundException('L\'image n\'existe pas');
        }
        
        $page =  $request->query->getInt('page', 1);
        $photos = $paginator->paginate( 
            $query,
            $page === 0 ? 1 : $page,
            5
        );
        $categories = $this->getDoctrine()->getRepository(Categorie::class)->findAll();

        // retourne la vue associée à cette route (méthode)
        return $this->render('home/categoryimg.html.twig', [
                'showImage' => $showImage,
                'photos' => $photos,
                'categories' => $categories
        ]);
    }
}

templates/home/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}categorie{% endblock %}

{% block body %}
 <nav id="menu">
        <ul>
            {% for category in categories %}
                <li><a href="{{ path ('categorie', {id:category.id}) }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
     </nav>
    <div class="navigation_cat"> 
        <h2 id="title">{{ categoriePage.name }}</h2>
        <h2>{{ knp_pagination_render(pictures) }}</h2>
    </div>
    <section id="grid">
    {% for picture in pictures %}
    <a href="{{ path ('showImage', {id:picture.id}) }}">
        <img src="{{ asset('uploads/images/featured/'~ picture.image)|imagine_filter('thumbnail') }}" alt="{{ picture.image }}">
    </a>
    {% endfor %}
    </section>
{% endblock %}

templates/home/categoryimg.html.twig
{% extends 'base.html.twig' %}

{% block title %}categorie{% endblock %}

{% block body %}
    {# <h1 id="title">{{ categoriePage.name }}</h1> #}
    <nav id="menu">
        <ul>
            {% for category in categories %}
                <li><a href="{{ path ('categorie', {id:category.id}) }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
     </nav>
    <section id="showImage">
        <div>
            <a href="{{ asset('uploads/images/featured/'~ showImage.image) }}"><img src="{{ asset('uploads/images/featured/'~ showImage.image)|imagine_filter('medium') }}" alt="{{ showImage.image }}"></a>
        </div>
        <div>
            <p>{{ showImage.description }}</p>
            <p class="date">{{ showImage.createdAt|date }}</p>
        </div>
        <div>
            <h3>{{ showImage.tags }}</h3>
        </div>
    </section>
    <div class="navigation_cat">
        <h2>{{ showImage.category.name }}</h2>
        <h2>{{ knp_pagination_render(photos) }}</h2>
    </div>
    <section id="grid">
    {# showImage correspond aux infos de notre image, à partir de cette image, nous allons chercher la catégorie reliée à l'image "showImage.category" et a partir de cette catégories, nous avons la possibilité de récupérer toutes les images liées a cette meme categorie soit "showImage.category.pictures #}
    {% for photo in photos %}
        {# 
            !== s'écrit en Twig : is not same as()
            === s'écrit en Twig : is same as()
        #}
        {% if photo.image is not same as(showImage.image) %}
            <a href="{{ path ('showImage', {id:photo.id}) }}">
                <img src="{{ asset('uploads/images/featured/'~ photo.image)|imagine_filter('thumbnail') }}" alt="{{ photo.image }}">
            </a>
        {% endif %}
    {% endfor %}
    </section>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil!{% endblock %}

{% block body %}
    
    {# <h1 id="title">Galerie d'images</h1> #}
    <nav id="menu">
        <ul>
            {% for category in categories %}
                <li><a href="{{ path ('categorie', {id:category.id}) }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
     </nav>
    <section id="grid">
        {% for picture in pictures %}
            <a href="{{ path ('showImage', {id:picture.id}) }}">
                <img src="{{ asset('uploads/images/featured/'~ picture.image)|imagine_filter('thumbnail') }}" alt="{{ picture.image }}">
            </a>
        {% endfor %}
    </section>
    <div class="navigation">
    {{ knp_pagination_render(pictures) }}
    </div>

{% endblock %}